"""
create_secrets.py — Run this ONCE to create .streamlit/secrets.toml
with a hashed password. Safe: never stores plaintext passwords.

Usage:
    python create_secrets.py
"""
import getpass, hashlib, secrets, os, pathlib

def generate_hash(password: str, salt: str) -> str:
    dk = hashlib.pbkdf2_hmac("sha256", password.encode(), salt.encode(), 260_000)
    return "pbkdf2:" + dk.hex()

print("\n=== Encalm Secrets Setup ===\n")
username = input("Admin username (e.g. admin): ").strip() or "admin"
password = getpass.getpass("Password (hidden): ")
confirm  = getpass.getpass("Confirm password: ")
if password != confirm:
    print("Passwords do not match. Exiting.")
    exit(1)

salt = secrets.token_hex(16)
hashed = generate_hash(password, salt)
entry  = f'{username} = "{salt}${hashed}"'

secrets_dir  = pathlib.Path(".streamlit")
secrets_path = secrets_dir / "secrets.toml"
secrets_dir.mkdir(exist_ok=True)

content = f"""# Auto-generated by create_secrets.py — do NOT commit this file to git.

[auth]

[auth.users]
{entry}

[auth.admins]
admins = ["{username}"]

# DATABASE_URL = "postgresql://user:password@host:5432/dbname?sslmode=disable"
# Leave commented out to use local SQLite (fine for local testing).
"""

secrets_path.write_text(content)
print(f"\n✅  Created {secrets_path}")
print(f"    Username: {username}")
print(f"    Password: (hidden)")
print("\nRestart 'streamlit run Home.py' to apply.\n")
